"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Vector = require("flo-vector2d");
const Bezier3 = require("flo-bezier3");
const Svg = require("../svg/svg");
const general_1 = require("./functions/general");
const two_prong_1 = require("./functions/two-prong");
const three_prong_1 = require("./functions/three-prong");
const draw_elem_1 = require("./functions/draw-elem/draw-elem");
class Generated {
    constructor(path, g) {
        this.path = path;
        this.g = g;
        this.elems = {
            twoProng_regular: [],
            twoProng_failed: [],
            twoProng_notAdded: [],
            twoProng_deleted: [],
            twoProng_holeClosing: [],
            looseBoundingBox: [],
            tightBoundingBox: [],
            oneProng: [],
            oneProngAtDullCorner: [],
            sharpCorner: [],
            dullCorner: [],
            minY: [],
            threeProng: [],
            boundingHull: [],
            mat: [],
            sat: [],
            cpNode: [],
            loop: [],
            loops: [],
        };
        this.timing = {
            simplify: [0, 0],
            holeClosers: [0, 0],
            oneAnd2Prongs: [0, 0],
            threeProngs: [0, 0],
            mats: [0, 0],
            sats: [0, 0]
        };
    }
}
exports.Generated = Generated;
class MatDebug {
    /**
     * @param fs - some useful functions.
     */
    constructor(draw) {
        /* The current path for which MATs are being found */
        this.generated = undefined;
        /* Generated by debug object for later inspection */
        this.generatedAll = new Map();
        // These are included only for quick debugging from console
        this.Bezier3 = Bezier3;
        this.Vector2d = Vector;
        this.Svg = Svg;
        this.directives = {
            stopAfterHoleClosers: false,
            stopAfterHoleClosersNum: undefined,
            stopAfterTwoProngs: false,
            stopAfterTwoProngsNum: undefined,
            stopAfterThreeProngs: false,
        };
        /**
         * These functions are meant to be used in the console, e.g. in the
         * console try typing d.fs.twoProng.traceConvergence(0);
         */
        this.fs = Object.assign({ draw }, general_1.generalDebugFunctions, { twoProng: two_prong_1.twoProngDebugFunctions, threeProng: three_prong_1.threeProngDebugFunctions, drawElem: draw_elem_1.drawElemFunctions });
    }
    createNewGenerated(loops, path, g) {
        this.generated = new Generated(path, g);
        this.generatedAll.set(loops, this.generated);
    }
}
exports.MatDebug = MatDebug;
