import type { DrawElemFunctions } from './functions/draw-elem/draw-elem.js';
import type { DebugElems } from './debug-elem-types.js';
/** @internal */
interface Debug {
    /** Generated by debug object for later inspection */
    elems: GeneratedElems;
    timing: Timing;
    /**
     * These functions are meant to be used in the console, e.g. in the
     * console try typing d.fs.twoProng.traceConvergence(0);
     */
    fs: DebugFunctions;
    directives: Directives;
}
/** @internal */
type GeneratedElems = {
    [T in keyof DebugElems]: DebugElems[T][];
};
/** @internal */
interface Timing {
    holeClosers: number;
    oneAnd2Prongs: number;
    threeProngs: number;
    sats: number;
    simplifyMat: number;
}
/** @internal */
interface DebugFunctions {
    drawElem: DrawElemFunctions;
}
/** @internal */
interface Directives {
    stopAfterHoleClosers: boolean;
    stopAfterHoleClosersNum: number;
    stopAfterTwoProngs: boolean;
    stopAfterTwoProngsNum: number;
    stopAfterThreeProngs: boolean;
    stopAfterThreeProngsNum: number;
}
declare function enableDebugForMat(debugOn: boolean): void;
export { Debug, GeneratedElems, Timing, DebugFunctions, Directives, enableDebugForMat };
