import { IGeneralDebugFunctions } from './functions/general.js';
import { DrawElemFunctions } from './functions/draw-elem/draw-elem.js';
import { DebugElems } from './debug-elem-types.js';
/** @internal */
interface Debug {
    /** Generated by debug object for later inspection */
    generated: Generated;
    /**
     * These functions are meant to be used in the console, e.g. in the
     * console try typing d.fs.twoProng.traceConvergence(0);
     */
    fs: IDebugFunctions;
    directives: IDirectives;
}
/** @internal */
type GeneratedElems = {
    [T in keyof DebugElems]: DebugElems[T][];
};
/** @internal */
interface ITiming {
    holeClosers: number;
    oneAnd2Prongs: number;
    threeProngs: number;
    sats: number;
    simplifyMat: number;
}
/** @internal */
interface Generated {
    elems: GeneratedElems;
    timing: ITiming;
}
/** @internal */
interface IDebugFunctions extends IGeneralDebugFunctions {
    drawElem: DrawElemFunctions;
}
/** @internal */
interface IDirectives {
    stopAfterHoleClosers: boolean;
    stopAfterHoleClosersNum: number;
    stopAfterTwoProngs: boolean;
    stopAfterTwoProngsNum: number;
    stopAfterThreeProngs: boolean;
    stopAfterThreeProngsNum: number;
}
declare function enableDebugForMat(debugOn: boolean): void;
export { Debug, GeneratedElems, ITiming, Generated, IDebugFunctions, IDirectives, enableDebugForMat };
