import type { DrawElemFunctions } from './functions/draw-elem/draw-elem.js';
import type { DebugElems } from './debug-elem-types.js';
import { drawElemFs } from './functions/draw-elem/draw-elem.js';


/** @internal */
interface Debug {
    /** Generated by debug object for later inspection */
    elems: GeneratedElems;
    timing: Timing;

    /**
     * These functions are meant to be used in the console, e.g. in the 
     * console try typing d.fs.twoProng.traceConvergence(0);
     */
    fs: DebugFunctions;
    directives: Directives;
}


/** @internal */
type GeneratedElems = { [T in keyof DebugElems]: DebugElems[T][] };


/** @internal */
interface Timing {
    holeClosers: number;
    oneAnd2Prongs: number;
    threeProngs: number;
    sats: number;
    simplifyMat: number;
}


/** @internal */
interface DebugFunctions {
    drawElem: DrawElemFunctions,
}


/** @internal */
interface Directives {
    stopAfterHoleClosers: boolean,
    stopAfterHoleClosersNum: number,
    stopAfterTwoProngs: boolean,
    stopAfterTwoProngsNum: number,
    stopAfterThreeProngs: boolean,
    stopAfterThreeProngsNum: number,
}


function enableDebugForMat(debugOn: boolean) {
    if (!debugOn) { 
        (window as any)._debug_ = undefined; 
        return;
    }

    let debug: Debug = (window as any)._debug_;

    debug = { 
        ...debug, 
        elems: { 
            ...debug?.elems,
            // @ts-ignore

            oneProng             : [],
            // oneProngAtDullCorner : [],
            twoProng             : [],
            // twoProng_regular     : [],
            // twoProng_failed      : [],
            // twoProng_notAdded    : [],
            // twoProng_deleted     : [],
            // twoProng_holeClosing : [],
            looseBoundingBox     : [],
            tightBoundingBox     : [],
            // sharpCorner          : [],
            // dullCorner           : [],
            vertex               : [],
            threeProng           : [],
            boundingHull         : [],
            mat                  : [],
            // sat                  : [],
            cpNode               : [],
            maxVertex            : [],
            leaves               : [],
            // culls                : [],
        },
        timing: {
            ...debug?.timing,
            holeClosers: 0,
            oneAnd2Prongs: 0,
            threeProngs: 0,
            sats: 0,
            simplifyMat: 0,
        },
        fs: {
            ...debug?.fs,
            drawElem: {
                ...debug?.fs?.drawElem,
                ...drawElemFs
            }
        },
        directives: {
            //...debug?.directives,
            ...debug?.directives,
            stopAfterHoleClosers: false,
            stopAfterHoleClosersNum: undefined!,
            stopAfterTwoProngs: false,
            stopAfterTwoProngsNum: undefined!,
            stopAfterThreeProngs: false,
            stopAfterThreeProngsNum: undefined!,
        }
    };

    (window as any)._debug_ = debug;
}


export { 
    Debug, GeneratedElems, Timing,
    DebugFunctions, Directives, enableDebugForMat
}
