"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.enableDebugForMat = exports.loopFromBeziers = exports.getClosestSquareDistanceToRect = exports.areBoxesIntersecting = exports.sweepLine = exports.drawElemFunctions = exports.getBoundaryPieceBeziers = exports.getCurveBetween = exports.getCurveToNext = exports.getClosestBoundaryPoint = exports.drawMat = exports.drawBranch = exports.getShapeBounds = exports.getPathsFromStr = exports.beziersToSvgPathStr = exports.simplifyMatMapOnly = exports.simplifyMat = exports.getBoundaryBezierPartsToNext = exports.getBoundaryBeziersToNext = exports.getBranches = exports.traverseEdges = exports.traverseVertices = exports.trimMat = exports.toScaleAxis = exports.findMats = exports.CpNode = exports.PointOnShape = void 0;
const cp_node_1 = require("./cp-node");
Object.defineProperty(exports, "CpNode", { enumerable: true, get: function () { return cp_node_1.CpNode; } });
const point_on_shape_1 = require("./point-on-shape");
Object.defineProperty(exports, "PointOnShape", { enumerable: true, get: function () { return point_on_shape_1.PointOnShape; } });
const find_mats_1 = require("./find-mats");
Object.defineProperty(exports, "findMats", { enumerable: true, get: function () { return find_mats_1.findMats; } });
const trim_mat_1 = require("./mat/trim-mat");
Object.defineProperty(exports, "trimMat", { enumerable: true, get: function () { return trim_mat_1.trimMat; } });
const to_scale_axis_1 = require("./to-scale-axis");
Object.defineProperty(exports, "toScaleAxis", { enumerable: true, get: function () { return to_scale_axis_1.toScaleAxis; } });
const traverse_edges_1 = require("./traverse-edges");
Object.defineProperty(exports, "traverseEdges", { enumerable: true, get: function () { return traverse_edges_1.traverseEdges; } });
const get_branches_1 = require("./get-branches");
Object.defineProperty(exports, "getBranches", { enumerable: true, get: function () { return get_branches_1.getBranches; } });
const traverse_vertices_1 = require("./traverse-vertices");
Object.defineProperty(exports, "traverseVertices", { enumerable: true, get: function () { return traverse_vertices_1.traverseVertices; } });
const debug_1 = require("./debug/debug");
Object.defineProperty(exports, "enableDebugForMat", { enumerable: true, get: function () { return debug_1.enableDebugForMat; } });
const branch_1 = require("./debug/functions/draw-elem/branch");
Object.defineProperty(exports, "drawBranch", { enumerable: true, get: function () { return branch_1.drawBranch; } });
const mat_1 = require("./debug/functions/draw-elem/mat");
Object.defineProperty(exports, "drawMat", { enumerable: true, get: function () { return mat_1.drawMat; } });
const get_closest_boundary_point_1 = require("./mat/closest-boundary-point/get-closest-boundary-point");
Object.defineProperty(exports, "getClosestBoundaryPoint", { enumerable: true, get: function () { return get_closest_boundary_point_1.getClosestBoundaryPoint; } });
const flo_boolean_1 = require("flo-boolean");
Object.defineProperty(exports, "beziersToSvgPathStr", { enumerable: true, get: function () { return flo_boolean_1.beziersToSvgPathStr; } });
Object.defineProperty(exports, "getPathsFromStr", { enumerable: true, get: function () { return flo_boolean_1.getPathsFromStr; } });
const get_shape_bounds_1 = require("./svg/get-shape-bounds");
Object.defineProperty(exports, "getShapeBounds", { enumerable: true, get: function () { return get_shape_bounds_1.getShapeBounds; } });
const get_boundary_beziers_to_next_1 = require("./get-boundary-beziers-to-next");
Object.defineProperty(exports, "getBoundaryBeziersToNext", { enumerable: true, get: function () { return get_boundary_beziers_to_next_1.getBoundaryBeziersToNext; } });
const get_boundary_bezier_parts_to_next_1 = require("./get-boundary-bezier-parts-to-next");
Object.defineProperty(exports, "getBoundaryBezierPartsToNext", { enumerable: true, get: function () { return get_boundary_bezier_parts_to_next_1.getBoundaryBezierPartsToNext; } });
const get_boundary_piece_beziers_1 = require("./mat/get-boundary-piece-beziers");
Object.defineProperty(exports, "getBoundaryPieceBeziers", { enumerable: true, get: function () { return get_boundary_piece_beziers_1.getBoundaryPieceBeziers; } });
const simplify_mat_1 = require("./simplify-mat");
Object.defineProperty(exports, "simplifyMat", { enumerable: true, get: function () { return simplify_mat_1.simplifyMat; } });
const simplify_mat_map_only_1 = require("./mat/simplify-mat-map-only");
Object.defineProperty(exports, "simplifyMatMapOnly", { enumerable: true, get: function () { return simplify_mat_map_only_1.simplifyMatMapOnly; } });
const draw_elem_1 = require("./debug/functions/draw-elem/draw-elem");
Object.defineProperty(exports, "drawElemFunctions", { enumerable: true, get: function () { return draw_elem_1.drawElemFunctions; } });
const get_curve_to_next_1 = require("./get-curve-to-next");
Object.defineProperty(exports, "getCurveToNext", { enumerable: true, get: function () { return get_curve_to_next_1.getCurveToNext; } });
const get_curve_between_1 = require("./get-curve/get-curve-between");
Object.defineProperty(exports, "getCurveBetween", { enumerable: true, get: function () { return get_curve_between_1.getCurveBetween; } });
const sweep_line_1 = require("./sweep-line/sweep-line");
Object.defineProperty(exports, "sweepLine", { enumerable: true, get: function () { return sweep_line_1.sweepLine; } });
const are_boxes_intersecting_1 = require("./sweep-line/are-boxes-intersecting");
Object.defineProperty(exports, "areBoxesIntersecting", { enumerable: true, get: function () { return are_boxes_intersecting_1.areBoxesIntersecting; } });
const get_closest_square_distance_to_rect_1 = require("./mat/geometry/get-closest-square-distance-to-rect");
Object.defineProperty(exports, "getClosestSquareDistanceToRect", { enumerable: true, get: function () { return get_closest_square_distance_to_rect_1.getClosestSquareDistanceToRect; } });
const loop_1 = require("./loop");
Object.defineProperty(exports, "loopFromBeziers", { enumerable: true, get: function () { return loop_1.loopFromBeziers; } });
//# sourceMappingURL=index.js.map