"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const loop_1 = require("../../../loop");
const complete_loop_1 = require("./complete-loop");
const get_initial_x_1 = require("./get-initial-x");
const get_loop_metrics_1 = require("./get-loop-metrics");
/**
 *
 * @param intersections
 * @param loopsTaken
 * @param loop
 * @param parent
 */
function completePath(intersections, loopsTaken, parent, loop) {
    // Each loop generated by xInfos in xStack will give rise to one 
    // componentLoop.
    let xStack = [get_initial_x_1.getInitialX(intersections, parent, loop)]; // Intersection stack        
    let takenXs = new Set(); // Taken intersections
    while (xStack.length) {
        let xInfo = xStack.pop();
        loopsTaken.add(xInfo.loop);
        if (takenXs.has(xInfo)) {
            continue;
        }
        let iLoop = get_loop_metrics_1.getLoopMetrics(xInfo);
        iLoop.beziers = complete_loop_1.completeLoop(intersections, takenXs, xStack, iLoop, xInfo);
        iLoop.loop = new loop_1.Loop(iLoop.beziers);
    }
}
exports.completePath = completePath;
